"""ajuste pooler

Revision ID: 64dbee169b1e
Revises: 
Create Date: 2026-03-19 20:26:06.358308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64dbee169b1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('codigo_part_number', sa.String(length=50), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('veiculo', sa.String(length=100), nullable=True),
    sa.Column('ano', sa.String(length=50), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_part_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pecas')
    # ### end Alembic commands ###
